### ISSUE TITLE
feat: Ability to define starting dealer seat

### ISSUE THREAD

**Issue by pernydev** [claudijo/poker-ts#10]
Hey! I love the project but due to my setup of it, it would be significantly easier to in the constructor define the seat the dealer chip should start at. I create new tables for every game due to the already complex infrastructure of my project so this would make the dealer chip actually move. No rush at all about this but it would be a nice feature to have.

TL;DR Make it so you can define where the dealer chip starts in the constructor

**Comment by claudijo** [comment]
At a quick glance a small change in the code would be to add the starting seat (dealer button) as an optional argument when calling start hand.

```
table.startHand(seat?: number)
```

Does that fit your use case?

**Comment by pernydev** [comment]
That looks perfect!
