### ISSUE TITLE
"Empty balance" player due to blind makes round stop

### ISSUE THREAD

**Issue by Shahito** [claudijo/poker-ts#7]
Hello. So, I hope I don't report an issue that is not one. The issue is kinda confusing.

During a two-player game, if one of the player's final balance (at the end of a round) is less or equal to the following round blind, the betting rounds are completed. But the second player that is the small blind never call on the big blind, and players never had the opportunity to fold. 

A game looks like this : 
(Blinds = 10/20)
## Round 1 :
  player_1_balance : 1000
  player_2_balance : 1000

  player_1 bet 980 (including the blind)
  player_2 call

  check, check, check...

## Showdown : 
  player_1 win

## Round 2 : 
  player_1_balance : 1980
  player_2_balance : 20
  
  ### After the blinds : 
  player_1_balance : 1970 (blind : 10)
  player_2_balance : 0 (blind : 20)

/!\ And here happens the issue, at this moment, the betting rounds are completed.

Actually, the only way to avoid getting this issue is to play with no blinds.

**Comment by claudijo** [comment]
Thanks for the feedback. I don't believe this is a bug though...

In the second round player 2 has the button, which means he/she pays the big blind with his/her last money as the hand is started. After that point there are no more rational actions that can be taken, consequently the betting rounds will be marked as completed and the only thing left in the round is showdown.

The small code example in the readme should encompass this type of situation and show what logical checks need to be done.

Please let me know if I've missed something.

**Comment by claudijo** [comment]
Actually this seems to be a bug, since the betting rounds end without player 1 having called the big blind. Sorry. Will have to take a look at this.
