### ISSUE TITLE
Types are not export whi

### ISSUE THREAD

**Issue by pop-srw** [claudijo/poker-ts#9]
The defined types in the library are not exported, which results in an inability to import these types from the library in external projects.

This issue prevents developers from using type definitions provided by the library, leading to potential type safety issues and reduced usability.

May be this may help developer to import types.
```
export type Card = {
    rank: '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | 'T' | 'J' | 'Q' | 'K' | 'A'
    suit: 'clubs' | 'diamonds' | 'hearts' | 'spades'
}

export type AutomaticAction = 'fold' | 'check/fold' | 'check' | 'call' | 'call any' | 'all-in'
export type Action = 'fold' | 'check' | 'call' | 'bet' | 'raise'
```

**Comment by claudijo** [comment]
Thanks for reporting this. Fixed in v1.3.0.
